### ISSUE TITLE
Issues with DataPermission's setPermission function in Swift library

### ISSUE THREAD

**Issue by niktszczegolny** [Backendless/Swift-SDK#250]
Hello,

I've encountered an issue with the `setPermission` function in the `DataPermission` class of the Backendless Swift library. The problem is twofold:

1. **Incorrect URL building**: The URL for the request is incorrectly constructed as it uses `permissionType` instead of `permissionType.rawValue`. This results in an incorrect URL, which prevents the function from working properly.

2. **Unable to set multiple permissions**: The current API doesn't support setting multiple permissions at once for a given user. This limitation makes it difficult to manage permissions efficiently when a user needs to have various access rights.

Here is the function that I'm referring to:

```swift
private func setPermission(entity: Any, permissionType: PermissionType, operation: PermissionOperation, userId: String?, roleName: String?, responseHandler: (() -> Void)!, errorHandler: ((Fault) -> Void)!)
```

Could you please look into these issues and provide a fix or workaround? It would greatly help in managing user roles and permissions more effectively.

Furthermore, it would be highly beneficial to allow not only multiple permissions to be set simultaneously, but also to enable setting permissions for multiple users at once. This way, a single API call could handle all the necessary permission assignments at once, greatly improving efficiency.

Thank you for your attention to this matter.

**Comment by olha-danylova** [comment]
Hello @niktszczegolny,

I've created an internal ticket BKNDLSS-32446 to investigate the `setPermission` issue and will check it ASAP.

According to these questions:

- Unable to set multiple permissions
- It would be highly beneficial to allow not only multiple permissions to be set simultaneously, but also to enable setting permissions for multiple users at once

could you please create a topic (without the iOS binding) on our [support forum](https://support.backendless.com)? I'm asking to create it without binding, because Swift-SDK library's structure corresponds to the structure of other SDKs and we should discuss a new methods idea for all other libraries.

**Comment by olha-danylova** [comment]
A new release 6.7.9 with fix is released.
